DROP TABLE IF EXISTS users, categories, events, locations, requests, compilations, compilations_event;

CREATE TABLE IF NOT EXISTS users
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name varchar (250)                         NOT NULL,
    email varchar(254)                         NOT NULL unique
);

CREATE TABLE IF NOT EXISTS categories
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name varchar (50)                          NOT NULL unique
);

CREATE TABLE IF NOT EXISTS locations
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    lat float8,
    lon float8
);


CREATE TABLE IF NOT EXISTS events
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    annotation varchar (2000)                  NOT NULL,
    category_id BIGINT                         references categories (id),
    confirmed_requests integer,
    created_on timestamp,
    description varchar (7000),
    event_date timestamp,
    initiator_id BIGINT                        references users (id),
    paid boolean,
    participant_limit integer,
    published_on timestamp,
    request_moderation boolean,
    state varchar (50),
--    state_action varchar (50),
    title varchar (120),
    location_id BIGINT                         references locations (id),
    views BIGINT
);

CREATE TABLE IF NOT EXISTS requests
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    created timestamp,
    event_id BIGINT                            references events (id),
    requester_id BIGINT                        references users (id),
    status varchar (50)
);

CREATE TABLE IF NOT EXISTS compilations
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    pinned boolean,
    title varchar (50)
);

CREATE TABLE IF NOT EXISTS compilations_event
(
    compilation_id BIGINT                      references compilations (id),
    event_id BIGINT                            references events (id)
);


